---
title: "Resume"
---

#**Qi Shao**

100 Have Avenue, #8H, New York, NY10032

(646)384-5338   

qs2200@columbia.edu

<br>

##EDUCATION


###Columbia University, Mailman School of Public Health                                         
Expected 05/2020 

**Master of Science in Biostatistics**

* Main Courses: Probability, Biostatistics Method, Data Science, Statistical Inference, Statistical Inference


###Shandong University, Jinan, China                                                                  
06/2018

**Bachelor of Science in Biological Technology **     

* Main Courses: Advanced Math, Linear Algebra, Probability Statistics, Biostatistics, Bioinformatics

* Publication: Effect of Gasotransmitters NO and H2S on Photosynthesis of Chinese Cabbage Seedlings under Chilling Stress". Journal of Shanxi University (Nat.Sci.Ed.), no. 40(3) :596-601,2017. 

* Honors & Awards: Scholarship for Academic Excellence (2016, 2017)        

<br>

##INTERNSHIP EXPERIENCE

###The Beijing Genomics Institute, Shenzhen, Guangdong                                         
07/2017–08/2017 

**Data Analyst Intern, Public Disease Department**

* Collected CNVs (copy number variations) associated with childhood obesity diabetic diseases from different races
* Used SNPsea software to compare the different interpretation of the same genes in various cells, find out the risk genes
* Learned Python under Linux OS, and ran analysis software in the cluster environment 

###Shanxi Environmental Science Research Center, Taiyuan, Shanxi                                 

06/2017–07/2017 

**Research Analyst **

* Participated in Shanxi section of National Ecology Changes Evaluation Project (2010-2015)
* Organized ecological data as well as climatic data and socioeconomic data
*Data analysis using Excel, conducted significant test of ecological parameters and meteorological factors

<br>

##ACADEMIC PROJECT

###Research on highly efficient synthesis of alpha lipoic acid using synthesis biological methods, Shandong University                                                          
04/2017-05/2018 

**Project Leader**

*	Organized team meetings for 10 times, brainstormed the experimental procedures and designs

*	Used QS (Quorum sensing) systems to construct cascade circuits in cells

*	Constructed an auto-induced AND gate that can response to rpoSP1 promoter and cell density to yield specific outputs

<br>

##VOLUNTEER LEADERSHIP AND INTEREST 

* Shandong University: Leader of Radio Program Team, interviewing people, program editing; 

* Water Quality Test of Urban Surface Water of Taiyuan, Shanxi: Team Leader, gathered and analyzed water samples, distributed questionnaires accordingly, wrote a report.

<br>

##SKILLS

* Computer and Software skills: Microsoft Office, R, Linux OS

* Languages: Chinese/English
